### ISSUE TITLE
[API design] Get Product details

### ISSUE THREAD

**Issue by haithamalnaeb** [HibatApp/hibat-backend#28]
As user I want to see product detail

Request parameter:
{peoductId}

Expected responses:

 - 200 success (products "model")
 - 404 No such item

**Comment by 1mehmood0** [comment]
Can i help you with this?
Will be great working on it being a newbie.

**Comment by haithamalnaeb** [comment]
@1pervysage0 sure, go ahead

Those tasks open for anyone and can start immediately

I hope the Pull Request Review help you to advance in your code and knowledge.
