### ISSUE TITLE
[API design] Get Products

### ISSUE THREAD

**Issue by haithamalnaeb** [HibatApp/hibat-backend#29]
As user I want to browse products

optional request parameters:
categoryId
q
page
pageLimit
sortBy

Expected responses:

    200 success (list of products "model")

**Comment by shamsmikdad** [comment]
what is the "q" parameters stand for?

**Comment by haithamalnaeb** [comment]
@shamsmikdad 
**q** stands for `query` in most search engines, this mean we can search using text, 
ex: I want to search for "book 123"
